### ISSUE TITLE
Simple plaintext output (feature request)

### ISSUE THREAD

**Issue by sbriskin** [Nhoya/gensum#4]
This script works fine but an output must be adopted for saving in file. So please add an option to save plain text output (w/o colors).

**Comment by stengun** [comment]
I think this is a good idea. File output can be useful for generating big hash files for fast file check, using common formats like "filename hash" each line.
What do you mean with colored output when writing on file? Has it a practical purpose?
Never mind: I understood what you meant.

**Comment by stengun** [comment]
Feature implemented in the latest commit, thank you for pointing out this missing feature
