### ISSUE TITLE
CRC MD5 checksums failed

### ISSUE THREAD

**Issue by sbriskin** [Nhoya/gensum#6]
I tried to check gensum itself from the file, made with new -o option.
That's the result:

<pre>
Checking given files
==========================================================
==> gensum <==============================================
1) md5: fb06f7d66e4197e5577609fd700631df WRONG!
2) sha1: 4cdb6e99cf4d4f623e0a608e57fb7bdb703167b0 OK!
3) sha256: 57b591aade8ed5060c8395950eac0cd7fa33bf74f4b157ad0ee5782978709787 OK!
4) ck: 2951164837 12740 WRONG!
==========================================================
</pre>

**Comment by stengun** [comment]
I have a couple of fixes to do on the dev branch  before merging, actually is not reliable. Try to force only md5 using -m option on another file you know is not changing. Specify the branch you're using when you open an issue. Last time I checked md5 was working fine as the others.

**Comment by sbriskin** [comment]
I was wrong!
'gensum -s all' saves only SHA checksums, not MD5 and CRC. So it can't find them in the saved file.
Sorry!
